config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/signup', to: 'users#new'
  root 'questions#index'
  resources :users
  resources :account_activations, only: [:edit]
  delete 'logout', to: 'sessions#destroy'
  resources :reset_passwords
  resource :comments, only: [:create,:edit,:update]
  resources :answers, only: [:create,:edit,:update,:new,:show]
  resources :questions, only: [:create,:edit,:update,:new,:show]
  get '/answer/:id/:question/sumar', to: 'answers#sumar'
  get '/question/:id/edit/sumar', to: 'questions#sumar'
  get '/answer/:id/:question/resta', to: 'answers#resta'
  get '/question/:id/edit/resta', to: 'questions#resta'
  get '/index/:order', to: 'questions#index'
  post '/search', to: 'questions#index'
  
  





end

app/models/question.rb
class Question < ApplicationRecord
  
  validates :tittle, presence:true, length: {maximum:50}
  validates :content,presence:true, length: {minimum:20}
  has_many :comments, :as => :imageable
  has_many :answers, :as => :imageable2
  belongs_to :user

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController


  def index
    delete_errors_a
    delete_errors
    delete_errors_2
    delete_errors_r
    delete_error_v_va
    delete_error
    
    if params[:order] == "nuevas"
      @questions = Question.order(created_at: :desc)
    elsif params[:order] == "masvotadas"
      @questions = Question.order(votes: :desc)
    elsif params[:order] == "masrespuestas"
      @questions = Question.order(respuestas: :desc)     
    else 
      if params[:order].nil?
        if !params["search"].nil?
          @questions = search(params["search"]["buscar"])
        else
          @questions = Question.order(created_at: :desc)
        end
      end
    end 
      @users = User.order(reputation: :desc)
   
  end
        




  def new
    @question  =  Question.new
  end




  def create

    @question = current_user.questions.build(question_params)
    @user = current_user
    if @question.save
      @question.update_attribute(:votes,0)
       @question.update_attribute(:respuestas,0)
      flash[:success] = "Tu pregunta se ha generado correctamente, has ganado un punto de reputación"
      @user.update_attribute(:reputation, @user.reputation + 1)
      redirect_to root_path
    else

      render 'new'
    end


  end




  def show
@question = Question.find(params[:id])
  end




  def update
    @question = Question.find(params[:id])
    
    if @question.update(question_params)
      flash[:success] = "Se ha editado la pregunta correctamente"
      redirect_to @question
    else
      render 'edit'

    end
  end



  def edit  
    @question = Question.find(params[:id])
  end  






  def sumar
    @question = Question.find(params[:id])
    @user = @question.user
    @current_user = current_user
    if logged?
      if @current_user.reputation < 5
        flash[:danger] = "Debes tener mas de 5 puntos para votar"
        redirect_to @question
      else
          if !@current_user.qvalidation["#{@question.id}"]

            @question.update_attribute(:votes,@question.votes + 1)
            @user.update_attribute(:reputation, @user.reputation + 1)
            flash[:success] = "Has votado correctamente, el usuario #{@user.name} ha ganado un punto de reputación"
            @hash = @current_user.qvalidation
            @hash["#{@question.id}"] = true
            @current_user.update_attribute(:qvalidation, @hash)
            redirect_to @question
          else
            flash[:danger] = "Ya has votado a esta pregunta"
            redirect_to @question    
          end
      end  
    else
      error_v
      redirect_to @question
    end
  end






  def resta
    @question = Question.find(params[:id])
    @user = @question.user
    @current_user = current_user
    if logged?
      if @current_user.reputation < 5
        flash[:danger] = "Debes tener mas de 5 puntos para votar"
        redirect_to @question
      else 
          if @current_user.qvalidation["#{@question.id}"]  
            @question.update_attribute(:votes,@question.votes - 1)
            @user.update_attribute(:reputation, @user.reputation - 1)
            flash[:success] = "Has quitado voto correctamente, el usuario #{@user.name} ha perdido un punto de reputación"
            @hash = @current_user.qvalidation
            @hash["#{@question.id}"] = false
            @current_user.update_attribute(:qvalidation, @hash)
            redirect_to @question
          else
            flash[:danger] = "No has votado a esta pregunta"
            redirect_to @question
              
          end  
      end  
    else
      error_v
      redirect_to @question
    end
  end






  def question_params
    params.require(:question).permit(:tittle,:content)
  end



end

app/helpers/questions_helper.rb
module QuestionsHelper


  def error_v
    delete_error_v_va
    session[:errors] = "Debes estar logueado para Votar esta pregunta"
  end

  def error_v?
    !session[:errors].nil?
  end

  def delete_error
    session.delete(:errors)
  end

  def error_r
    delete_error_v_va
    session[:error_r] = "Debes tener mas de 5 puntos para votar"
  end

  def error_r?
    !session[:error_r].nil?
  end

  def delete_errors_r
    session.delete(:error_r)
  end

  def timer(t)
    aux = t.split(" ")

    if aux.count == 2
      if aux[1] == "minutes"
        aux[1] = "minutos"
      elsif aux[1] == "minute"
        aux[1] = "Minuto"
        else
        aux[1] = "dias"
      end

    elsif aux.count == 3
      aux[0] = "alrededor de "
      aux[2] = "horas"
    elsif aux.count == 4
      aux[0] = "menos"
      aux[1] = "de"
      aux[2] = "un"
      aux[3] = "Minuto"


    end

    aux.join(" ")
  end


  def search(substring)


    @questions = Question.all
    @questions_result = []
    @questions.each do |f|
      if f.tittle.downcase.include?(substring) or f.content.downcase.include?(substring.downcase)
        @questions_result.push(f)
      end  
    end
    @questions_result
  end





end

app/views/questions/_form.html.erb
<%= form_for( @question) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label "Cúal es tu pregunta?" %>
    <%= f.text_field :tittle , class:'form-control'%>
    <br>
    <%= f.text_area :content, class:'form-control' %>



    <br>
    <%= f.submit "Preguntar",class:'' %>

<% end %>

app/views/questions/edit.html.erb
<%= render 'layouts/header' %>
<div class="container">

	<div class="row">
	  <div class="col-sm-6 col-sm-offset-2">
	    <%= render 'form' %>

	  </div>


	</div>
</div>	

app/views/questions/index.html.erb
<%= render 'layouts/header' %>
<div class="container">
 <% flash.each do |type,content| %>
    <div class="alert alert-<%=type%>">
     <%= content %>
    </div>
    <% end %>
  <div class="row">
    <div class="col-sm-8">
      <ul class="nav nav-tabs nav-justified">
        <li role="presentation" > <%= link_to "nuevas", '/index/nuevas' %></li>
        <li role="presentation"><%= link_to "Mas votadas", '/index/masvotadas' %></li>
        <li role="presentation"><%= link_to "Mas Repuestas", '/index/masrespuestas' %></li>

      </ul>
      <br>
      <% if !@questions.empty? %>
        <% @questions.each do |f| %>
            <div class="row filas">
              <div class="col-sm-5 ">
                <div class="row">
                  <div class="col-sm-4">
                    <div>
                      <span gris><%= f.votes %></span>
                      <span class="gris block" >votos</span>

                    </div>
                  </div>
                  <div class="col-sm-4 padding">
                    <div>
                      <span><%= f.answers.count %></span>
                      <span class="gris">Respuestas</span>
                    </div>
                  </div>
                  <div class="col-sm-4 padding">
                    <div>
                      <span><%= f.comments.count %></span>
                      <span class="gris">Comentarios</span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-sm-7">
                <div class="row">
                  <div class="col-sm-12">
                    <%= markdown(link_to f.tittle, question_path(f)) %>
                  </div>
                  <% user = f.user %>
                  <div class="col-sm-12 col-sm-offset-10">

                  <span ><%= link_to user.name, user%>    <span class="reputation"><%=user.reputation%></span> </span> 
                  </div>
                  <div class="col-sm-12 col-sm-offset-10">

                  <span class="gris"><%= timer(time_ago_in_words(f.created_at)) %></span> 
                  </div>
                </div>
              </div>
            </div>
        <% end %>
      <% else %>
      No hay preguntas
      <%end %>
    </div>
    <div class="col-sm-4">
      <div class="row">
        <% if logged? %>
          <div class="col-sm-6 center">  
            <h3><%= @questions.count %> Preguntas</h3>
          </div>
          <div class="col-sm-6 vertical">  
            <%= link_to "Hacer una pregunta",new_question_path, class:'btn btn-primary' %>
          </div>
        <% else %>
          <div class="col-sm-6 center">  
            <h3><%= @questions.count %> Preguntas</h3>
          </div>
          <div class="col-sm-6 vertical">  
            <%= link_to "Hacer una pregunta",login_path, class:'btn btn-primary' %>
          </div>
        <% end %>
        <div class="col-sm-12 margen">
          <div class="col-sm-12 center">
            <span>Top reputaciones</span>
          </div>
          <% @users.each do |f| %>
            <div class="col-sm-12 center ">
              <span><%= link_to f.name , f %></span><span class="reputation"><%= f.reputation %></span>
            </div>
          <% end %> 
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/questions/new.html.erb
<%= render 'layouts/header' %>	
	<div class="row">
	  <div class="col-sm-6 col-sm-offset-2">
	    <%= render 'form' %>

	  </div>


	</div>

app/views/questions/prueba.html.erb
<div>hola mundo</div>

app/views/questions/show.html.erb
<%= render 'layouts/header' %>
<div class="container">
   <% flash.each do |type,content| %>
    <div class="alert alert-<%=type%>">
     <%= content %>
    </div>
    <% end %>
  <div class="row ">
    <div class="col-sm-8">
      <% if error_v? %>
          <div>Debes estar logueado para votar (<%= link_to "iniciar sesion", login_path %>)</div>
      <% elsif error_r? %>
          <div>Debes tener mas de 5 puntos para votar</div>
      <% elsif error_v_a? %>
          <div>Debes estar logueado para votar (<%= link_to "iniciar sesion", login_path %>)</div>
      <% end %>

      <span><h2><%= markdown(@question.tittle) %></h2></span>
    </div>
    <div class="col-sm-4">
      <% if logged? %>
          <%= link_to "Hacer una pregunta",new_question_path, class:'btn btn-primary' %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-1">
      <div class="row">
        <div class="col-sm-12">
          <a href="/question/<%= @question.id %>/edit/sumar"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>
        </div>

      </div>
      <div class="row">
        <div class="col-sm-12">
         <span class="move"><%= @question.votes == nil ? 0 : @question.votes %></span>
        </div>

      </div>
      <div class="row">
        <div class="col-sm-12">
          <a href="/question/<%= @question.id %>/edit/resta"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
        </div>
      </div>
    </div>
    <div class="col-sm-11 move2">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default row">
            <div class="panel-body">
              <span class="pregunta"><%= markdown(@question.content )%></span>
              <% user = @question.user %>
              <% if logged? %>
                <% if current_user.id == user.id%>
                  <div> <%= link_to "Editar", edit_question_path(@question) %></div>
                <% end %>
              <% end %>
              <div class="col-sm-6 col-sm-offset-9">
                <span class="display comment "><%= user.name %> <span class=" reputation"><%=user.reputation%></span></span>
              </div>



            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <% @question.comments.each do |f| %>
              <div class="panel panel-default row">
                <div class="panel-body">
                  <span class="comment"><%= markdown(f.content) %></span>
                  <div class="col-sm-12 col-sm-offset-9">
                    <% user = User.find_by(name: f.username) %>
                    <span class="display comment"><%= user.name %> <span class=" reputation"><%=user.reputation == nil ? 0:user.reputation%></span></span>

                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <% if logged? %>
      <div class="row">
        <div class="col-sm-8">
          <%= form_for(:comment,url: comments_path) do |f| %>
              <% current_errors %>

              <% if errors? %>
                <% current_errors.each do |f| %>
                  <ul>
                    <li><%= f %></li>
                  </ul>
                <%end %>

              <%end %>
            <%= f.text_area :content, class:'form-control' %>
              <%= hidden_field_tag :question, @question.id %>
              <%= hidden_field_tag :answer, "no"%>
            <%= f.submit "Comentar", class:'btn btn-primary' %>
          <%end %>
        </div>
      </div>
      <%else %>
          <div class="row">
            <div class="col-sm-8">
              <%= link_to "Iniciar sesion para comentar",login_path %>
            </div>
          </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-12">
     <h2><%= @question.answers.count %> respuestas</h2>
    </div>
    <% @question.answers.each do |f| %>
    
      <div class="col-sm-1">
        <div class="row">
          <div class="col-sm-12">
            <a href="/answer/<%= f.id %>/<%= @question.id %>/sumar"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a>

          </div>

        </div>
        <div class="row">
          <div class="col-sm-12">
            <span class="move"><%= f.votes == nil ? 0 : f.votes %></span>
          </div>

        </div>
        <div class="row">
          <div class="col-sm-12">
            <a href="/answer/<%= f.id %>/<%= @question.id %>/resta"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a>
          </div>
        </div>
      </div>
      <div class="col-sm-11 move2">
        <div class="row">
          <div class="col-sm-12">
            <div class="panel panel-default row">
              <div class="panel-body">
                
                <span><%= markdown(f.content) %></span>
                <% user = User.find_by(name: f.username) %>
                <% if logged? %>
                <% if current_user.id == user.id%>
                  <div> <%= link_to "Editar", edit_answer_path(f) %></div>
                <% end %>
              <% end %>
                <div class="col-sm-6 col-sm-offset-9">
                  <% user = User.find_by(name: f.username) %>
                  <span class="display comment"><%= user.name %> <span class=" reputation"><%= user.reputation%></span></span>

                </div>
                <div class="col-sm-12 col-sm-offset-9">

                  <span class="gris"><%= timer(time_ago_in_words(f.created_at)) %></span> 
                  </div>
              </div>
            </div>
          </div>

        </div>
        <div class="row ">
          <div class="col-sm-12">
            <% f.comments.each do |t| %>
                <div class="panel panel-default row">
                  <div class="panel-body">
                    <span class="comment"><%= markdown(t.content) %></span>
                    <div class="col-sm-6 col-sm-offset-9">
                      <% user = User.find_by(name: t.username) %>
                      <span class="display comment"><%= user.name %> <span class=" reputation"><%=user.reputation%></span></span>

                    </div>
                  </div>
                </div>
            <% end %>
          </div>
        </div>
        <% if logged? %>
        <div class="row">
          <div class="col-sm-12 margen ">
            <%= form_for(:comment,url: comments_path) do |t| %>
                <% current_errors_2 %>

                <% if errors_2? %>
                    <% current_errors_2.each do |t| %>
                        <ul>
                          <% if f.error  %>
                          <li><%= t %></li>
                        <% end %>
                        </ul>
                    <%end %>

                <%end %>
                <%= t.text_area :content, class:'form-control ' %>
                <%= hidden_field_tag :answer_id, f.id %>
                <%= hidden_field_tag :answer, "si" %>
                <%= hidden_field_tag :question, @question.id %>

                <%= t.submit "Comentar", class:'btn btn-primary' %>
            <%end %>
          </div>
        </div>
        <%else %>
            <div class="row">
              <div class="col-sm-8">
                <%= link_to "Iniciar sesion para Comentar",login_path %>
              </div>
            </div>
        <% end %>
      </div>
    
    <% end %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-2">
      <h2>Responder</h2>
    </div>
    <div class="col-sm-12">
     <% if logged? %>
          <%= form_for(:answer,url: answers_path) do |f| %>
              <% current_errors_a %>

              <% if errors_a? %>
                  <% current_errors_a.each do |f| %>
                      <ul>
                        <li><%= f %></li>
                      </ul>
                  <%end %>

              <%end %>
              <%= f.text_area :content, class:'form-control textarea ' %>
              <%= hidden_field_tag :question, @question.id %>
              <%= f.submit "Responder", class:'btn btn-primary' %>
          <%end %>
      <% else %>
          <%= link_to "Iniciar sesion para Responder",login_path %>
      <% end %>

    </div>

  </div>
</div>