config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/login', to: 'sessions#create'
  get '/login', to: 'sessions#new'
  get '/signup', to: 'users#new'
  root 'questions#index'
  resources :users
  resources :account_activations, only: [:edit]
  delete 'logout', to: 'sessions#destroy'
  resources :reset_passwords
  resource :comments, only: [:create,:edit,:update]
  resources :answers, only: [:create,:edit,:update,:new,:show]
  resources :questions, only: [:create,:edit,:update,:new,:show]
  get '/answer/:id/:question/sumar', to: 'answers#sumar'
  get '/question/:id/edit/sumar', to: 'questions#sumar'
  get '/answer/:id/:question/resta', to: 'answers#resta'
  get '/question/:id/edit/resta', to: 'questions#resta'
  get '/index/:order', to: 'questions#index'
  post '/search', to: 'questions#index'
  
  





end

app/controllers/reset_passwords_controller.rb
class ResetPasswordsController < ApplicationController
  before_action :get_user, only: [:edit, :update]

  def new
  end

  def create

    @user = User.find_by(email: params[:resset][:email])

    if @user
      UserMailer.password_reset(@user).deliver_now
      flash[:info] = "Se te ha enviado un correo para que reestrablezcas tu contraseña"
      redirect_to root_url
    else
      flash[:warning] = "No se ha encontrado el correo"
      render 'new'
    end
  end

  def edit

  end

  def update

      if @user.update_attributes(user_params)
        flash[:info] = "Se he reestablecido la contraseña"
        logged(@user)
        redirect_to root_url
      else
        render 'edit'
      end
  end



  def user_params
    params.require(:user).permit(:password,:password_confirmation)
  end

  def get_user
    @user = User.find_by(email: params[:email])
  end

end

app/helpers/reset_passwords_helper.rb
module ResetPasswordsHelper
end

app/views/reset_passwords/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2" >
    <%= form_for(@user,url: reset_password_path(params[:id])) do |f|%>
        <%= render 'shared/error_messages' %>
        <%= hidden_field_tag :email, @user.email %>
        <%= f.label :password %>
        <%= f.password_field :password, class:'form-control' %>
        <%= f.label :password_confirm %>
        <%= f.password_field :password_confirm, class:'form-control' %>
        <%= f.submit "Cambiar contraseña", class:'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/reset_passwords/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-2" >
    <%= form_for(:resset,url: reset_passwords_path) do |f|%>
        <%= f.label :email %>
        <%= f.text_field :email, class:'form-control' %>
        <br>
        <%= f.submit "Solicitar cambio de contraseña", class:'btn btn-primary' %>
    <% end %>
  </div>
</div>